### ISSUE TITLE
Reminders not showing error / success messages.

### ISSUE THREAD

**Issue by yli-hallila** [Luukuton/TohsakaBot#17]
When creating new reminders the bot doesn't reply anything.

# Steps to reproduce

a) `?remindme tomorrow at 9; no error`

Or

b) `?remindme -d today at 17:00 -m no success message`

But when checking `?reminders` the reminder was successfully made!

**Comment by Luukuton** [comment]
A small correction: the message was not send when the reminder had a link in the message parameter.  Fixed [here](https://github.com/Luukuton/TohsakaBot/commit/7caea967b0cb86e2655a003707053164678be4df).
