### ISSUE TITLE
Reminder details

### ISSUE THREAD

**Issue by samaij** [Luukuton/TohsakaBot#19]
It might be useful to be able to get more information about a reminder using a command.

Example: `?reminderdetails 123`

The output could be similar to what is displayed on the website:
- ID
- Datetime
- Message
- If it's repeated and how often
- Channel

**Comment by Luukuton** [comment]
[Done](https://github.com/Luukuton/TohsakaBot/commit/f997bd19ff9b3e15523c6427dcce828131bb281c).
