### ISSUE TITLE
Trigger details

### ISSUE THREAD

**Issue by samaij** [Luukuton/TohsakaBot#20]
It might be useful to be able to get more information about a trigger using a command.

Example: ?triggerdetails 123

The output could be similar to what is displayed on the website:

- ID
- Options (also better explained than "100% any" maybe?)
- (Server ID)
- Phrase
- Full reply (output of ?triggers is truncated)

**Comment by Luukuton** [comment]
Done: [commit #1](https://github.com/Luukuton/TohsakaBot/commit/595c9ca190f3f4e4b9ba069107531d6e56b12f2e), [commit #2](https://github.com/Luukuton/TohsakaBot/commit/28dc30b733360534ab08626e35f799247661005e). Author will soon be added as well.
