### ISSUE TITLE
Multiple triggers with the same phrase

### ISSUE THREAD

**Issue by samaij** [Luukuton/TohsakaBot#22]
It might be smarter if the bot didn't allow users to create multiple triggers with the same phrase, because the bot now posts all the responses for the trigger at the same time.

Alternatively, the bot could choose one from the messages at random.

**Comment by Luukuton** [comment]
Will probably choose one reply at random while having some sort of limit how many triggers with the same phrase can exist simultaneously (3-10).

**Comment by Luukuton** [comment]
The bot now chooses one at random if there are multiple triggers with same phrases. Commit here https://github.com/Luukuton/TohsakaBot/commit/1a03a4de1766af28802656330d4ebacb85ac58dc.
