### ISSUE TITLE
Timed ranks

### ISSUE THREAD

**Issue by Furydar** [Luukuton/TohsakaBot#9]
Add support for timed ranks (for example, add the ability to make the bot give you a rank every day at a certain time and also remove it at a certain time).

**Comment by Luukuton** [comment]
Will be added.

**Comment by Luukuton** [comment]
Added here: https://github.com/Luukuton/TohsakaBot/commit/7130ec371b2de94de36e7c67a5de27849fd6f702

It's still an early version and there are probably some bugs, so I'm keeping this issue open.
